name: SDK Go
# Go SDK integration tests

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  go-120:
    uses: ./.github/workflows/_core-sdk.yml
    with:
      sdk-type: go
      go-version: '1.20'
      commands: |
        go build ./...
        go test ./...
      artifact-name: go-coverage-120
      artifact-path: sdk/go/coverage.out

  go-121:
    uses: ./.github/workflows/_core-sdk.yml
    with:
      sdk-type: go
      go-version: '1.21'
      commands: |
        go build ./...
        go test ./...
      artifact-name: go-coverage-121
      artifact-path: sdk/go/coverage.out