name: SDK Python
# Python SDK integration tests

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  python-38:
    uses: ./.github/workflows/_core-sdk.yml
    with:
      sdk-type: python
      python-version: '3.8'
      commands: |
        pip install maturin
        maturin develop
        python -m pytest tests/
      artifact-name: python-wheel-38
      artifact-path: sdk/python/target/wheels/*.whl

  python-39:
    uses: ./.github/workflows/_core-sdk.yml
    with:
      sdk-type: python
      python-version: '3.9'
      commands: |
        pip install maturin
        maturin develop
        python -m pytest tests/
      artifact-name: python-wheel-39
      artifact-path: sdk/python/target/wheels/*.whl

  python-310:
    uses: ./.github/workflows/_core-sdk.yml
    with:
      sdk-type: python
      python-version: '3.10'
      commands: |
        pip install maturin
        maturin develop
        python -m pytest tests/
      artifact-name: python-wheel-310
      artifact-path: sdk/python/target/wheels/*.whl

  python-311:
    uses: ./.github/workflows/_core-sdk.yml
    with:
      sdk-type: python
      python-version: '3.11'
      commands: |
        pip install maturin
        maturin develop
        python -m pytest tests/
      artifact-name: python-wheel-311
      artifact-path: sdk/python/target/wheels/*.whl